name: Web Server Monitor

on:
  schedule:
    - cron: '*/1 * * * *'  # Runs every 1 minutes
  workflow_dispatch:  # Allows manual trigger

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get HTTP Status
        run: |
          TIMESTAMP=$(date +"%Y-%m-%d %H:%M:%S")
          STATUS_CODE=$(curl -o /dev/null -s -w "%{http_code}" https://en.wikipedia.org/wiki/Main_Page)
          echo "$TIMESTAMP - Status: $STATUS_CODE" >> status_log.txt

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add status_log.txt
          git commit -m "Update status log" || exit 0
          git push
